apiVersion: batch/v1
kind: Job
metadata:
  name: db-create-{{ .Release.Revision }}
  namespace: {{ dig "global" "db" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  backoffLimit: 10
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: db 
          image: jambonz/db-create:0.8.0-rc5
          env:
            - name: JAMBONES_MYSQL_HOST
              value: {{ .Values.mysql.host }}
            - name: JAMBONES_MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: JAMBONES_MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: JAMBONES_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MYSQL_PASSWORD
          imagePullPolicy: Always
      restartPolicy: OnFailure
