# mysql configuration
mysql: 
  image: mysql:5.7
  host: 
  database: jambones
  user: 
  storage: 10Gi
  secret: 
# redis configuration used by Node.js app that need to connect
redis: 
  image: redis:alpine
  host: 
  port: "6379"
