{{- if not .Values.global.kong.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-server
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  rules:
    - host: {{ required "hostname for the REST API" .Values.api.hostname }}
      http:
        paths:
        - backend:
            service:
              name: api-server
              port: 
                number:  {{ .Values.api.httpPort }}
          path: /
          pathType: Prefix
{{- end}}
