apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
{{ include "common.labels" . | indent 4 }}
  name: webapp
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: webapp
      port: 3001
      targetPort: 3001
  type: NodePort
  selector:
    app: webapp
