apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: heplify-server
  labels:
    app: heplify-server
{{ include "common.labels" . | indent 4 }}
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  serviceName: heplify-server
  replicas: 1
  selector:
    matchLabels:
      app: heplify-server
  template:
    metadata:
      labels:
        app: heplify-server
      annotations:
        {{- if .Values.global.podAnnotations }}
        {{ toYaml .Values.global.podAnnotations | default "" | nindent 8 }}
        {{- end }}
        {{- if .Values.heplifyServer.podAnnotations }}
        {{ toYaml .Values.heplifyServer.podAnnotations | default "" | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | default "" | nindent 8 }}
      {{- end }}
      containers:
        - name: heplify-server
          image: {{ .Values.heplifyServer.image }}
          args: ['./heplify-server', '-config', '/etc/heplify-server.toml']
          ports:
            - containerPort: 9060
              protocol: UDP
            - containerPort: 9096
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/heplify-server.toml
              name: heplify-server-conf
              subPath: heplify-server.toml
      volumes:
      - name: heplify-server-conf
        configMap:
          name: heplify-server-conf
          items:
          - key: heplify-server.toml
            path: heplify-server.toml
