{{- if .Values.global.cassandra.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  labels:
    app: jaeger-collector
{{ include "common.labels" . | indent 4 }}
  namespace: {{ dig "global" "monitoring" "namespace" .Release.Namespace (.Values | merge (dict)) | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-collector
  template:
    metadata:
      labels:
        app: jaeger-collector
      annotations:
        {{- if .Values.global.podAnnotations }}
        {{ toYaml .Values.global.podAnnotations | default "" | nindent 8 }}
        {{- end }}
        {{- if .Values.jaegerCollector.podAnnotations }}
        {{ toYaml .Values.jaegerCollector.podAnnotations | default "" | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: jaeger-collector
        image: {{ .Values.jaegerCollector.image }}
        args: ["--log-level=info", "--cassandra.servers=cassandra:9042", "--cassandra.keyspace={{ .Values.cassandra.keyspace }}"]
        ports:
        - containerPort: 14250
          name: grpc-collect
        - containerPort: 14268
          name: http-collect
        - containerPort: 14269
          name: healthcheck
{{- end}}
